print("WELCOME,")
Firstname = input("Enter Your First Name: \n")
Middlename = input("Enter Your Middle Name: \n")
Lastname = input("Enter Your Last Name: \n")
Age = int(input("Enter Your Age: \n"))
Dateofbirth = input("Enter Your Date Of BIrth: \n")
Gender = input("Enter Your Gender: \n")
Phonenumber = int(input("Enter Your Phone Number: \n"))
Address = input("Enter Your Address: \n")

print("                                                                      ALOE ACADEMY")
print("STUDENT'S CONTACT LIST")
print(f"Welcome {Firstname},")

contact_list = []
contact_list.append(f"{Firstname}") 
contact_list.append(f"{Middlename}")
contact_list.append(f"{Lastname}")
contact_list.append(f"{Age}")
contact_list.append(f"{Dateofbirth}")
contact_list.append(f"{Gender}")
contact_list.append(f"{Phonenumber}")
contact_list.append(f"{Address}")
print(contact_list)